#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable

import optuna


KEY_VALUE_PATTERN = re.compile(r"^(?P<indent>\s*)(?P<key>[A-Za-z0-9_]+)(?P<sep>\s*=\s*)(?P<value>[-+0-9.eE]+)(?P<trail>\s*)$")
MAX_SPEED_KEY_PATTERN = re.compile(r"^max_.*_speed$")


@dataclass(frozen=True)
class SearchRange:
    low: float
    high: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Optimize PID config parameters with Optuna by minimizing goal_reach_time. "
            "Parameters matching max_*_speed are excluded from optimization."
        )
    )
    parser.add_argument(
        "--pid-config",
        type=Path,
        default=Path("test/control/configs/control/pid.toml"),
        help="Path to PID config TOML file",
    )
    parser.add_argument(
        "--control-app",
        type=Path,
        default=Path("build/control_test_app"),
        help="Path to control_test_app executable",
    )
    parser.add_argument(
        "--analyzer-script",
        type=Path,
        default=Path("test/control/analyze_control_log.py"),
        help="Path to analyze_control_log.py",
    )
    parser.add_argument(
        "--metrics-path",
        type=Path,
        default=Path("test/control/logs/analysis/metrics.json"),
        help="Path to metrics.json generated by analyzer",
    )
    parser.add_argument("--n-trials", type=int, default=50, help="Number of Optuna trials")
    parser.add_argument("--timeout", type=int, default=0, help="Optimization timeout seconds (0: no timeout)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for sampler")
    parser.add_argument(
        "--study-name",
        type=str,
        default="pid_goal_reach_time",
        help="Optuna study name",
    )
    parser.add_argument(
        "--storage",
        type=str,
        default="",
        help="Optuna storage URL (empty: in-memory)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("test/control/logs/optuna"),
        help="Directory to save optimization artifacts",
    )
    parser.add_argument(
        "--failure-penalty",
        type=float,
        default=1e6,
        help="Objective value used when a trial fails",
    )
    parser.add_argument(
        "--restore-original-on-finish",
        action="store_true",
        help="Restore original pid.toml after optimization instead of applying best params",
    )
    return parser.parse_args()


def to_abs(path: Path, workspace_root: Path) -> Path:
    if path.is_absolute():
        return path
    return (workspace_root / path).resolve()


def parse_numeric_toml(toml_path: Path) -> tuple[list[str], Dict[str, float], Dict[str, int]]:
    lines = toml_path.read_text(encoding="utf-8").splitlines()
    params: Dict[str, float] = {}
    line_map: Dict[str, int] = {}

    for idx, line in enumerate(lines):
        match = KEY_VALUE_PATTERN.match(line)
        if not match:
            continue
        key = match.group("key")
        value = float(match.group("value"))
        params[key] = value
        line_map[key] = idx

    if not params:
        raise ValueError(f"No numeric key-value pairs found in {toml_path}")

    return lines, params, line_map


def update_numeric_toml(
    lines: list[str],
    line_map: Dict[str, int],
    updated_values: Dict[str, float],
) -> str:
    new_lines = list(lines)
    for key, value in updated_values.items():
        if key not in line_map:
            continue
        line_idx = line_map[key]
        line = new_lines[line_idx]
        match = KEY_VALUE_PATTERN.match(line)
        if not match:
            continue
        new_value = f"{value:.12g}"
        new_lines[line_idx] = (
            f"{match.group('indent')}{match.group('key')}{match.group('sep')}{new_value}{match.group('trail')}"
        )

    return "\n".join(new_lines) + "\n"


def build_search_space(params: Dict[str, float]) -> Dict[str, SearchRange]:
    space: Dict[str, SearchRange] = {}
    for key, value in params.items():
        if MAX_SPEED_KEY_PATTERN.match(key):
            continue

        if "lookahead" in key:
            low = max(0.05, value * 0.25 if value > 0.0 else 0.05)
            high = max(2.0, value * 4.0 if value > 0.0 else 2.0)
        elif key.endswith("_ki"):
            low = 0.0
            high = max(0.5, value * 8.0 if value > 0.0 else 0.5)
        elif key.endswith("_kp"):
            low = 0.0
            high = max(3.0, value * 6.0 if value > 0.0 else 3.0)
        elif key.endswith("_kd"):
            low = 0.0
            high = max(2.0, value * 6.0 if value > 0.0 else 2.0)
        else:
            if value >= 0.0:
                low = 0.0
                high = max(1.0, value * 6.0 if value > 0.0 else 1.0)
            else:
                low = value * 3.0
                high = abs(value) * 3.0

        if not high > low:
            high = low + 1.0

        space[key] = SearchRange(low=low, high=high)

    return space


def run_command(command: Iterable[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(command),
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )


def load_goal_reach_time(metrics_path: Path) -> tuple[float, Dict[str, float]]:
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    if "goal_reach_time" not in metrics:
        raise KeyError(f"goal_reach_time is missing in {metrics_path}")
    return float(metrics["goal_reach_time"]), metrics


def main() -> int:
    args = parse_args()
    workspace_root = Path(__file__).resolve().parents[2]

    pid_config = to_abs(args.pid_config, workspace_root)
    control_app = to_abs(args.control_app, workspace_root)
    analyzer_script = to_abs(args.analyzer_script, workspace_root)
    metrics_path = to_abs(args.metrics_path, workspace_root)
    output_dir = to_abs(args.output_dir, workspace_root)

    if not pid_config.exists():
        print(f"pid config not found: {pid_config}", file=sys.stderr)
        return 1
    if not control_app.exists():
        print(f"control app not found: {control_app}", file=sys.stderr)
        return 1
    if not analyzer_script.exists():
        print(f"analyzer script not found: {analyzer_script}", file=sys.stderr)
        return 1

    output_dir.mkdir(parents=True, exist_ok=True)

    original_text = pid_config.read_text(encoding="utf-8")
    backup_path = pid_config.with_suffix(pid_config.suffix + ".optuna.bak")
    backup_path.write_text(original_text, encoding="utf-8")

    base_lines, base_params, line_map = parse_numeric_toml(pid_config)
    search_space = build_search_space(base_params)
    if not search_space:
        print("No searchable parameters found (all matched max_*_speed?)", file=sys.stderr)
        return 1

    fixed_params = {k: v for k, v in base_params.items() if k not in search_space}

    print("Optuna PID optimization start")
    print(f"  pid_config: {pid_config}")
    print(f"  control_app: {control_app}")
    print(f"  analyzer_script: {analyzer_script}")
    print(f"  metrics_path: {metrics_path}")
    print(f"  n_trials: {args.n_trials}")
    print(f"  timeout: {args.timeout}")
    print(f"  fixed keys (not optimized): {sorted(fixed_params.keys())}")
    print(f"  optimized keys: {sorted(search_space.keys())}")

    sampler = optuna.samplers.TPESampler(seed=args.seed)
    study = optuna.create_study(
        direction="minimize",
        sampler=sampler,
        study_name=args.study_name,
        storage=(args.storage if args.storage else None),
        load_if_exists=bool(args.storage),
    )

    trial_logs: list[dict] = []

    def objective(trial: optuna.Trial) -> float:
        sampled = {
            key: trial.suggest_float(key, rng.low, rng.high)
            for key, rng in search_space.items()
        }
        merged = dict(base_params)
        merged.update(sampled)

        pid_config.write_text(update_numeric_toml(base_lines, line_map, merged), encoding="utf-8")

        run_result = run_command([str(control_app)], cwd=workspace_root)
        if run_result.returncode != 0:
            trial.set_user_attr("status", "control_app_failed")
            trial.set_user_attr("control_app_output", run_result.stdout[-5000:])
            trial_logs.append(
                {
                    "trial": trial.number,
                    "status": "control_app_failed",
                    "objective": args.failure_penalty,
                }
            )
            return args.failure_penalty

        analyze_result = run_command(["uv", "run", str(analyzer_script)], cwd=workspace_root)
        if analyze_result.returncode != 0 or not metrics_path.exists():
            trial.set_user_attr("status", "analyzer_failed")
            trial.set_user_attr("analyzer_output", analyze_result.stdout[-5000:])
            trial_logs.append(
                {
                    "trial": trial.number,
                    "status": "analyzer_failed",
                    "objective": args.failure_penalty,
                }
            )
            return args.failure_penalty

        try:
            goal_reach_time, metrics = load_goal_reach_time(metrics_path)
        except Exception as exc:
            trial.set_user_attr("status", "metrics_parse_failed")
            trial.set_user_attr("metrics_error", str(exc))
            trial_logs.append(
                {
                    "trial": trial.number,
                    "status": "metrics_parse_failed",
                    "objective": args.failure_penalty,
                }
            )
            return args.failure_penalty

        if not math.isfinite(goal_reach_time) or goal_reach_time <= 0.0:
            goal_reach_time = args.failure_penalty
            trial.set_user_attr("status", "goal_not_reached")
        else:
            trial.set_user_attr("status", "ok")

        trial.set_user_attr("goal_reach_time", goal_reach_time)
        trial.set_user_attr("rmse", metrics.get("rmse"))
        trial.set_user_attr("heading_error_rmse", metrics.get("heading_error_rmse"))

        trial_logs.append(
            {
                "trial": trial.number,
                "status": trial.user_attrs.get("status", "unknown"),
                "objective": goal_reach_time,
                "params": sampled,
            }
        )

        print(
            f"trial={trial.number} objective(goal_reach_time)={goal_reach_time:.6f} "
            f"status={trial.user_attrs.get('status', 'unknown')}"
        )
        return goal_reach_time

    optimize_timeout = args.timeout if args.timeout > 0 else None

    try:
        study.optimize(objective, n_trials=args.n_trials, timeout=optimize_timeout)
    except KeyboardInterrupt:
        print("Optimization interrupted by user", file=sys.stderr)

    complete_trials = [t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE]
    if not complete_trials:
        pid_config.write_text(original_text, encoding="utf-8")
        print("No successful trial completed. Restored original pid.toml", file=sys.stderr)
        return 2

    best_trial = study.best_trial
    best_params = dict(base_params)
    best_params.update(best_trial.params)

    if args.restore_original_on_finish:
        pid_config.write_text(original_text, encoding="utf-8")
        final_config_mode = "restored_original"
    else:
        pid_config.write_text(update_numeric_toml(base_lines, line_map, best_params), encoding="utf-8")
        final_config_mode = "applied_best"

    report = {
        "study_name": study.study_name,
        "best_trial": best_trial.number,
        "best_value": best_trial.value,
        "best_params": best_trial.params,
        "fixed_params": fixed_params,
        "search_space": {k: {"low": v.low, "high": v.high} for k, v in search_space.items()},
        "n_trials": len(study.trials),
        "n_complete": len(complete_trials),
        "backup_path": str(backup_path),
        "pid_config": str(pid_config),
        "final_config_mode": final_config_mode,
    }

    report_path = output_dir / "optuna_pid_result.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    trials_path = output_dir / "optuna_trial_log.json"
    trials_path.write_text(json.dumps(trial_logs, indent=2, ensure_ascii=False), encoding="utf-8")

    print("Optimization complete")
    print(f"  best_trial: {best_trial.number}")
    print(f"  best_goal_reach_time: {best_trial.value}")
    print(f"  report: {report_path}")
    print(f"  trials_log: {trials_path}")
    print(f"  backup: {backup_path}")
    print(f"  pid_final_mode: {final_config_mode}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
