#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
import re
import statistics
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, Tuple

import optuna


SECTION_HEADER_PATTERN = re.compile(r"^\s*\[(?P<section>[A-Za-z0-9_.-]+)\]\s*$")
KEY_VALUE_PATTERN = re.compile(
    r"^(?P<indent>\s*)(?P<key>[A-Za-z0-9_]+)(?P<sep>\s*=\s*)(?P<value>[-+0-9.eE]+)(?P<trail>\s*)$"
)


@dataclass(frozen=True)
class SearchSpec:
    section: str
    key: str
    low: float
    high: float
    kind: str  # "int" or "float"


SEARCH_SPECS: tuple[SearchSpec, ...] = (
    SearchSpec("hough", "min_votes", 14, 24, "int"),
    SearchSpec("hough", "max_lines", 40, 70, "int"),
    SearchSpec("hough", "min_segment_length", 0.35, 0.90, "float"),
    SearchSpec("hough", "merge_rho", 0.10, 0.24, "float"),
    SearchSpec("hough", "merge_theta", 0.04, 0.10, "float"),
    SearchSpec("association", "max_association_distance", 0.22, 0.35, "float"),
    SearchSpec("association", "gate_threshold", 4.0, 6.5, "float"),
    SearchSpec("ransac", "max_iterations", 70, 140, "int"),
    SearchSpec("ransac", "min_inliers", 3, 6, "int"),
    SearchSpec("ransac", "min_inlier_ratio", 0.20, 0.40, "float"),
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Optimize hough+rancac localization parameters with Optuna by minimizing ATE"
    )
    parser.add_argument(
        "--localization-config",
        type=Path,
        default=Path("test/localization/configs/localization/ekf_hough_ransac.toml"),
        help="Path to hough_ransac localization TOML",
    )
    parser.add_argument(
        "--localization-app",
        type=Path,
        default=Path("build/localization_test_app"),
        help="Path to localization_test_app executable",
    )
    parser.add_argument(
        "--analyzer-script",
        type=Path,
        default=Path("test/localization/analyze_localization_log.py"),
        help="Path to analyze_localization_log.py",
    )
    parser.add_argument(
        "--render",
        action="store_true",
        help="Run localization_test_app with --render (default: off)",
    )
    parser.add_argument(
        "--metrics-path",
        type=Path,
        default=Path("test/localization/logs/analysis/localization_test/metrics.json"),
        help="Path to metrics.json generated by analyzer",
    )
    parser.add_argument("--n-trials", type=int, default=20, help="Number of Optuna trials")
    parser.add_argument("--timeout", type=int, default=0, help="Optimization timeout seconds (0: no timeout)")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for sampler")
    parser.add_argument(
        "--eval-runs",
        type=int,
        default=3,
        help="Number of repeated runs per trial to reduce randomness",
    )
    parser.add_argument(
        "--eval-reducer",
        type=str,
        default="median",
        choices=["median", "mean"],
        help="How to aggregate ATE values from repeated runs",
    )
    parser.add_argument(
        "--study-name",
        type=str,
        default="localization_hough_ransac_ate",
        help="Optuna study name",
    )
    parser.add_argument(
        "--storage",
        type=str,
        default="",
        help="Optuna storage URL (empty: in-memory)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("test/localization/logs/optuna"),
        help="Directory to save optimization artifacts",
    )
    parser.add_argument(
        "--failure-penalty",
        type=float,
        default=1e6,
        help="Objective value used when a trial fails",
    )
    parser.add_argument(
        "--restore-original-on-finish",
        action="store_true",
        help="Restore original config after optimization instead of applying best params",
    )
    return parser.parse_args()


def to_abs(path: Path, workspace_root: Path) -> Path:
    if path.is_absolute():
        return path
    return (workspace_root / path).resolve()


def parse_numeric_toml_by_section(
    toml_path: Path,
) -> tuple[list[str], Dict[Tuple[str, str], float], Dict[Tuple[str, str], int]]:
    lines = toml_path.read_text(encoding="utf-8").splitlines()
    params: Dict[Tuple[str, str], float] = {}
    line_map: Dict[Tuple[str, str], int] = {}
    current_section = ""

    for idx, line in enumerate(lines):
        section_match = SECTION_HEADER_PATTERN.match(line)
        if section_match:
            current_section = section_match.group("section")
            continue

        key_match = KEY_VALUE_PATTERN.match(line)
        if not key_match:
            continue

        key = key_match.group("key")
        value = float(key_match.group("value"))
        section_key = (current_section, key)
        params[section_key] = value
        line_map[section_key] = idx

    if not params:
        raise ValueError(f"No numeric key-value pairs found in {toml_path}")

    return lines, params, line_map


def update_numeric_toml_by_section(
    lines: list[str],
    line_map: Dict[Tuple[str, str], int],
    updated_values: Dict[Tuple[str, str], float],
) -> str:
    new_lines = list(lines)
    for section_key, value in updated_values.items():
        if section_key not in line_map:
            continue
        line_idx = line_map[section_key]
        line = new_lines[line_idx]
        match = KEY_VALUE_PATTERN.match(line)
        if not match:
            continue
        new_value = f"{value:.12g}"
        new_lines[line_idx] = (
            f"{match.group('indent')}{match.group('key')}{match.group('sep')}{new_value}{match.group('trail')}"
        )

    return "\n".join(new_lines) + "\n"


def run_command(command: Iterable[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(command),
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )


def load_ate(metrics_path: Path) -> tuple[float, Dict[str, object]]:
    metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    ate = float(metrics["ate"])
    return ate, metrics


def main() -> int:
    args = parse_args()
    workspace_root = Path(__file__).resolve().parents[2]

    localization_config = to_abs(args.localization_config, workspace_root)
    localization_app = to_abs(args.localization_app, workspace_root)
    analyzer_script = to_abs(args.analyzer_script, workspace_root)
    metrics_path = to_abs(args.metrics_path, workspace_root)
    output_dir = to_abs(args.output_dir, workspace_root)

    if not localization_config.exists():
        print(f"localization config not found: {localization_config}", file=sys.stderr)
        return 1
    if not localization_app.exists():
        print(f"localization app not found: {localization_app}", file=sys.stderr)
        return 1
    if not analyzer_script.exists():
        print(f"analyzer script not found: {analyzer_script}", file=sys.stderr)
        return 1
    if args.eval_runs <= 0:
        print("--eval-runs must be >= 1", file=sys.stderr)
        return 1

    output_dir.mkdir(parents=True, exist_ok=True)

    original_text = localization_config.read_text(encoding="utf-8")
    backup_path = localization_config.with_suffix(localization_config.suffix + ".optuna.bak")
    backup_path.write_text(original_text, encoding="utf-8")

    base_lines, base_params, line_map = parse_numeric_toml_by_section(localization_config)

    for spec in SEARCH_SPECS:
        if (spec.section, spec.key) not in base_params:
            print(f"Search key not found in TOML: [{spec.section}] {spec.key}", file=sys.stderr)
            return 1

    print("Optuna localization optimization start")
    print(f"  localization_config: {localization_config}")
    print(f"  localization_app: {localization_app}")
    print(f"  analyzer_script: {analyzer_script}")
    print(f"  metrics_path: {metrics_path}")
    print(f"  n_trials: {args.n_trials}")
    print(f"  timeout: {args.timeout}")
    print(f"  eval_runs: {args.eval_runs}")
    print(f"  eval_reducer: {args.eval_reducer}")

    sampler = optuna.samplers.TPESampler(seed=args.seed)
    study = optuna.create_study(
        direction="minimize",
        sampler=sampler,
        study_name=args.study_name,
        storage=(args.storage if args.storage else None),
        load_if_exists=bool(args.storage),
    )

    trial_logs: list[dict] = []

    def objective(trial: optuna.Trial) -> float:
        sampled_values: Dict[Tuple[str, str], float] = {}
        sampled_log: Dict[str, float] = {}

        for spec in SEARCH_SPECS:
            name = f"{spec.section}.{spec.key}"
            if spec.kind == "int":
                value = float(trial.suggest_int(name, int(spec.low), int(spec.high)))
            else:
                value = float(trial.suggest_float(name, spec.low, spec.high))
            sampled_values[(spec.section, spec.key)] = value
            sampled_log[name] = value

        merged = dict(base_params)
        merged.update(sampled_values)

        localization_config.write_text(
            update_numeric_toml_by_section(base_lines, line_map, merged),
            encoding="utf-8",
        )

        app_command = [str(localization_app), "--render"] if args.render else [str(localization_app), "--no-render"]
        run_ates: list[float] = []
        run_results: list[str] = []
        run_update_counts: list[int | None] = []

        for run_index in range(args.eval_runs):
            run_result = run_command(app_command, cwd=workspace_root)
            if run_result.returncode != 0:
                trial.set_user_attr("status", "localization_app_failed")
                trial.set_user_attr("failed_eval_run", run_index)
                trial.set_user_attr("localization_app_output", run_result.stdout[-5000:])
                trial_logs.append(
                    {
                        "trial": trial.number,
                        "status": "localization_app_failed",
                        "failed_eval_run": run_index,
                        "objective": args.failure_penalty,
                        "params": sampled_log,
                    }
                )
                return args.failure_penalty

            analyze_result = run_command([sys.executable, str(analyzer_script)], cwd=workspace_root)
            if analyze_result.returncode != 0 or not metrics_path.exists():
                trial.set_user_attr("status", "analyzer_failed")
                trial.set_user_attr("failed_eval_run", run_index)
                trial.set_user_attr("analyzer_output", analyze_result.stdout[-5000:])
                trial_logs.append(
                    {
                        "trial": trial.number,
                        "status": "analyzer_failed",
                        "failed_eval_run": run_index,
                        "objective": args.failure_penalty,
                        "params": sampled_log,
                    }
                )
                return args.failure_penalty

            try:
                ate, metrics = load_ate(metrics_path)
            except Exception as exc:
                trial.set_user_attr("status", "metrics_parse_failed")
                trial.set_user_attr("failed_eval_run", run_index)
                trial.set_user_attr("metrics_error", str(exc))
                trial_logs.append(
                    {
                        "trial": trial.number,
                        "status": "metrics_parse_failed",
                        "failed_eval_run": run_index,
                        "objective": args.failure_penalty,
                        "params": sampled_log,
                    }
                )
                return args.failure_penalty

            result = str(metrics.get("result", "unknown"))
            if result != "success" or not math.isfinite(ate) or ate <= 0.0:
                trial.set_user_attr("status", "run_failure_or_invalid_ate")
                trial.set_user_attr("failed_eval_run", run_index)
                trial_logs.append(
                    {
                        "trial": trial.number,
                        "status": "run_failure_or_invalid_ate",
                        "failed_eval_run": run_index,
                        "objective": args.failure_penalty,
                        "ate": ate if math.isfinite(ate) else None,
                        "result": result,
                        "params": sampled_log,
                    }
                )
                return args.failure_penalty

            run_ates.append(ate)
            run_results.append(result)
            run_update_counts.append((metrics.get("observation_update") or {}).get("count"))

        objective_value = statistics.median(run_ates) if args.eval_reducer == "median" else statistics.fmean(run_ates)
        status = "ok"

        trial.set_user_attr("status", status)
        trial.set_user_attr("ate", objective_value)
        trial.set_user_attr("ate_runs", run_ates)
        trial.set_user_attr("result", "success")
        trial.set_user_attr("eval_runs", args.eval_runs)
        trial.set_user_attr("eval_reducer", args.eval_reducer)
        trial.set_user_attr(
            "update_count",
            min(count for count in run_update_counts if count is not None) if any(count is not None for count in run_update_counts) else None,
        )

        trial_logs.append(
            {
                "trial": trial.number,
                "status": status,
                "objective": objective_value,
                "ate": objective_value,
                "ate_runs": run_ates,
                "result": "success",
                "update_count": min(count for count in run_update_counts if count is not None) if any(count is not None for count in run_update_counts) else None,
                "eval_runs": args.eval_runs,
                "eval_reducer": args.eval_reducer,
                "params": sampled_log,
            }
        )

        print(
            f"trial={trial.number} objective(ATE)={objective_value:.6f} "
            f"ate_runs={[round(v, 6) for v in run_ates]} reducer={args.eval_reducer} status={status}"
        )
        return objective_value

    optimize_timeout = args.timeout if args.timeout > 0 else None

    try:
        study.optimize(objective, n_trials=args.n_trials, timeout=optimize_timeout)
    except KeyboardInterrupt:
        print("Optimization interrupted by user", file=sys.stderr)

    complete_trials = [t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE]
    if not complete_trials:
        localization_config.write_text(original_text, encoding="utf-8")
        print("No successful trial completed. Restored original localization TOML", file=sys.stderr)
        return 2

    best_trial = study.best_trial
    best_params: Dict[Tuple[str, str], float] = dict(base_params)
    for spec in SEARCH_SPECS:
        name = f"{spec.section}.{spec.key}"
        best_value = best_trial.params[name]
        best_params[(spec.section, spec.key)] = float(best_value)

    if args.restore_original_on_finish:
        localization_config.write_text(original_text, encoding="utf-8")
        final_config_mode = "restored_original"
    else:
        localization_config.write_text(
            update_numeric_toml_by_section(base_lines, line_map, best_params),
            encoding="utf-8",
        )
        final_config_mode = "applied_best"

    report = {
        "study_name": study.study_name,
        "best_trial": best_trial.number,
        "best_value": best_trial.value,
        "best_params": best_trial.params,
        "search_space": {
            f"{spec.section}.{spec.key}": {
                "low": spec.low,
                "high": spec.high,
                "kind": spec.kind,
            }
            for spec in SEARCH_SPECS
        },
        "n_trials": len(study.trials),
        "n_complete": len(complete_trials),
        "backup_path": str(backup_path),
        "localization_config": str(localization_config),
        "final_config_mode": final_config_mode,
    }

    report_path = output_dir / "optuna_localization_result.json"
    report_path.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    trials_path = output_dir / "optuna_localization_trial_log.json"
    trials_path.write_text(json.dumps(trial_logs, indent=2, ensure_ascii=False), encoding="utf-8")

    print("Optimization complete")
    print(f"  best_trial: {best_trial.number}")
    print(f"  best_ATE: {best_trial.value}")
    print(f"  report: {report_path}")
    print(f"  trials_log: {trials_path}")
    print(f"  backup: {backup_path}")
    print(f"  localization_final_mode: {final_config_mode}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
