#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import re
import shlex
import subprocess
from collections import Counter
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

DIAG_PREFIX = "[ransac_diag]"
KV_PATTERN = re.compile(r"([a-zA-Z0-9_]+)=([^\s]+)")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="One-shot RANSAC debug pipeline: run, capture, analyze, visualize"
    )
    parser.add_argument(
        "--app",
        default="./build/localization_test_app",
        help="Command to run localization test app",
    )
    parser.add_argument(
        "--scenario",
        default="",
        help="Scenario toml path passed as positional arg to app (optional)",
    )
    parser.add_argument(
        "--render",
        action="store_true",
        help="Pass --render to localization_test_app",
    )
    parser.add_argument(
        "--log",
        type=Path,
        default=Path("test/localization/logs/localization_test.log"),
        help="Localization log path generated by app",
    )
    parser.add_argument(
        "--stdout-log",
        type=Path,
        default=Path("test/localization/logs/ransac_debug_stdout.log"),
        help="Path to save app stdout/stderr",
    )
    parser.add_argument(
        "--diag-log",
        type=Path,
        default=Path("test/localization/logs/ransac_diag.log"),
        help="Path to save extracted [ransac_diag] lines",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("test/localization/logs/analysis/ransac_debug"),
        help="Output directory for metrics, plots, and timeline",
    )
    parser.add_argument("--stride", type=int, default=1, help="Render every N-th lidar frame")
    parser.add_argument("--max-frames", type=int, default=0, help="0=all frames")
    parser.add_argument("--fps", type=int, default=6, help="GIF frames per second")
    parser.add_argument("--no-gif", action="store_true", help="Skip GIF export")
    parser.add_argument(
        "--skip-run",
        action="store_true",
        help="Do not run app, analyze existing logs only",
    )
    return parser.parse_args()


def run_localization_test(args: argparse.Namespace) -> int:
    command = shlex.split(args.app)
    if args.scenario:
        command.append(args.scenario)
    if args.render:
        command.append("--render")

    completed = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    args.stdout_log.parent.mkdir(parents=True, exist_ok=True)
    args.stdout_log.write_text(completed.stdout, encoding="utf-8")

    diag_lines = [line for line in completed.stdout.splitlines() if DIAG_PREFIX in line]
    args.diag_log.parent.mkdir(parents=True, exist_ok=True)
    args.diag_log.write_text("\n".join(diag_lines) + ("\n" if diag_lines else ""), encoding="utf-8")

    print(f"App exit code: {completed.returncode}")
    print(f"Saved stdout: {args.stdout_log}")
    print(f"Captured diagnostics: {len(diag_lines)} -> {args.diag_log}")
    return completed.returncode


def parse_header_and_rows(log_path: Path) -> Tuple[Dict[str, str], List[str], List[Dict[str, str]]]:
    if not log_path.exists():
        raise FileNotFoundError(f"Localization log not found: {log_path}")

    header: Dict[str, str] = {}
    columns: List[str] = []
    rows: List[Dict[str, str]] = []

    with log_path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue

            if line.startswith("#"):
                content = line[1:].strip()
                if "=" in content:
                    key, value = content.split("=", 1)
                    header[key.strip()] = value.strip()
                elif content.startswith("columns:"):
                    columns = [col.strip() for col in content.split(":", 1)[1].split(",")]
                continue

            if not columns:
                columns = [col.strip() for col in line.split(",")]
                continue

            parts = [part.strip() for part in next(csv.reader([line]))]
            if len(parts) != len(columns) or parts == columns:
                continue
            rows.append(dict(zip(columns, parts)))

    if not columns:
        raise ValueError("CSV columns not found in localization log")

    return header, columns, rows


def parse_diag_rows(diag_log_path: Path) -> List[Dict[str, str]]:
    if not diag_log_path.exists():
        return []
    rows: List[Dict[str, str]] = []
    for raw in diag_log_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or DIAG_PREFIX not in line:
            continue
        row: Dict[str, str] = {}
        for key, value in KV_PATTERN.findall(line):
            row[key] = value
        if row:
            rows.append(row)
    return rows


def parse_points_robot(serialized: str) -> List[Tuple[float, float]]:
    if not serialized:
        return []
    points: List[Tuple[float, float]] = []
    for token in serialized.split(";"):
        if not token:
            continue
        parts = token.split(":")
        if len(parts) != 2:
            continue
        try:
            points.append((float(parts[0]), float(parts[1])))
        except ValueError:
            continue
    return points


def parse_segments(serialized: str) -> List[Tuple[float, float, float, float]]:
    if not serialized:
        return []
    segments: List[Tuple[float, float, float, float]] = []
    for token in serialized.split("|"):
        parts = token.split(":")
        if len(parts) != 4:
            continue
        try:
            x1, y1, x2, y2 = float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3])
        except ValueError:
            continue
        segments.append((x1, y1, x2, y2))
    return segments


def transform_point_robot_to_world(
    x_r: float, y_r: float, pose_x: float, pose_y: float, theta: float
) -> Tuple[float, float]:
    cos_t = math.cos(theta)
    sin_t = math.sin(theta)
    return pose_x + (cos_t * x_r) - (sin_t * y_r), pose_y + (sin_t * x_r) + (cos_t * y_r)


def resolve_scenario_path(header: Dict[str, str], scenario_arg: str) -> Path:
    if scenario_arg:
        return Path(scenario_arg).resolve()
    raw = header.get("scenario_config")
    if raw:
        return Path(raw).resolve()
    return Path("test/localization/configs/localization.toml").resolve()


def parse_scenario_and_map(scenario_path: Path) -> Tuple[Path, float, Tuple[float, float]]:
    map_yaml_rel = None
    in_map_section = False
    for raw in scenario_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            in_map_section = line == "[map]"
            continue
        if in_map_section and line.startswith("yaml_path"):
            map_yaml_rel = line.split("=", 1)[1].strip().strip('"')
            break

    if map_yaml_rel is None:
        raise ValueError(f"yaml_path not found in scenario: {scenario_path}")

    map_yaml_path = (scenario_path.parent / map_yaml_rel).resolve()
    image_rel = None
    resolution = None
    origin_xy = None
    for raw in map_yaml_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if line.startswith("image:"):
            image_rel = line.split(":", 1)[1].strip()
        elif line.startswith("resolution:"):
            resolution = float(line.split(":", 1)[1].strip())
        elif line.startswith("origin:"):
            txt = line.split(":", 1)[1].strip().removeprefix("[").removesuffix("]")
            vals = [float(v.strip()) for v in txt.split(",")]
            origin_xy = (vals[0], vals[1])

    if image_rel is None or resolution is None or origin_xy is None:
        raise ValueError(f"Invalid map yaml: {map_yaml_path}")

    map_image_path = (map_yaml_path.parent / image_rel).resolve()
    return map_image_path, resolution, origin_xy


def as_int(rows: List[Dict[str, str]], key: str, default: int = 0) -> np.ndarray:
    values = []
    for row in rows:
        raw = row.get(key)
        try:
            values.append(int(raw) if raw is not None else default)
        except ValueError:
            values.append(default)
    return np.asarray(values, dtype=int)


def save_timeseries(path: Path, title: str, y_label: str, values: np.ndarray) -> None:
    if values.size == 0:
        return
    fig, ax = plt.subplots(figsize=(10, 4), dpi=120)
    ax.plot(np.arange(values.size), values, lw=1.2)
    ax.set_title(title)
    ax.set_xlabel("diag frame index")
    ax.set_ylabel(y_label)
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def save_histogram(path: Path, title: str, values: np.ndarray) -> None:
    if values.size == 0:
        return
    fig, ax = plt.subplots(figsize=(8, 4), dpi=120)
    bins = np.arange(values.min(), values.max() + 2) - 0.5
    ax.hist(values, bins=bins, edgecolor="white", alpha=0.9)
    ax.set_title(title)
    ax.set_xlabel("count")
    ax.set_ylabel("frequency")
    ax.grid(alpha=0.25)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def save_reject_bar(path: Path, reject_counter: Counter) -> None:
    if not reject_counter:
        return
    labels = list(reject_counter.keys())
    values = [reject_counter[label] for label in labels]
    fig, ax = plt.subplots(figsize=(9, 4), dpi=120)
    ax.bar(labels, values, alpha=0.9)
    ax.set_title("Reject reason counts")
    ax.set_ylabel("count")
    ax.grid(axis="y", alpha=0.25)
    ax.tick_params(axis="x", rotation=20)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def save_stage1_segment_grid(path: Path, diag_rows: List[Dict[str, str]], max_frames: int = 9) -> None:
    frames = [(index, parse_segments(row.get("stage1_segments", ""))) for index, row in enumerate(diag_rows)]
    frames = [(index, segments) for index, segments in frames if segments]
    if not frames:
        return

    sample_count = min(max_frames, len(frames))
    if sample_count == 1:
        chosen = [frames[0]]
    else:
        sample_indices = np.linspace(0, len(frames) - 1, num=sample_count).round().astype(int)
        chosen = [frames[idx] for idx in sample_indices]

    cols = 3
    rows_count = int(np.ceil(sample_count / cols))
    fig, axes = plt.subplots(rows_count, cols, figsize=(12, 4 * rows_count), dpi=120)
    axes = np.atleast_1d(axes).reshape(rows_count, cols)

    for plot_index in range(rows_count * cols):
        ax = axes[plot_index // cols, plot_index % cols]
        if plot_index >= sample_count:
            ax.axis("off")
            continue

        frame_index, segments = chosen[plot_index]
        xs: List[float] = []
        ys: List[float] = []
        for x1, y1, x2, y2 in segments:
            ax.plot([x1, x2], [y1, y2], "-", linewidth=2.0)
            xs.extend([x1, x2])
            ys.extend([y1, y2])

        if xs and ys:
            pad = 0.3
            ax.set_xlim(min(xs) - pad, max(xs) + pad)
            ax.set_ylim(min(ys) - pad, max(ys) + pad)

        ax.set_aspect("equal")
        ax.set_title(f"frame={frame_index}, segments={len(segments)}")
        ax.grid(alpha=0.25)

    fig.suptitle("Stage1 extracted segments (robot frame)")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def build_diag_metrics(diag_rows: List[Dict[str, str]]) -> Dict:
    stage1 = as_int(diag_rows, "stage1_extracted")
    stage2 = as_int(diag_rows, "stage2_matches")
    gate = as_int(diag_rows, "gate_passed")
    accepted = as_int(diag_rows, "accepted")

    reject_counter = Counter(row.get("reject", "") for row in diag_rows if "reject" in row)
    segment_counts = np.asarray(
        [len(parse_segments(row.get("stage1_segments", ""))) for row in diag_rows], dtype=int
    )
    segment_lengths: List[float] = []
    for row in diag_rows:
        for x1, y1, x2, y2 in parse_segments(row.get("stage1_segments", "")):
            segment_lengths.append(float(np.hypot(x2 - x1, y2 - y1)))
    seg_len = np.asarray(segment_lengths, dtype=float)

    return {
        "frames": int(len(diag_rows)),
        "accepted_count": int(np.sum(accepted == 1)),
        "accepted_rate": float(np.mean(accepted == 1)) if accepted.size > 0 else 0.0,
        "stage1_extracted": {
            "mean": float(np.mean(stage1)) if stage1.size > 0 else 0.0,
            "median": float(np.median(stage1)) if stage1.size > 0 else 0.0,
            "distribution": {str(k): int(v) for k, v in sorted(Counter(stage1).items())},
        },
        "stage2_matches": {
            "mean": float(np.mean(stage2)) if stage2.size > 0 else 0.0,
            "zero_rate": float(np.mean(stage2 == 0)) if stage2.size > 0 else 0.0,
            "distribution": {str(k): int(v) for k, v in sorted(Counter(stage2).items())},
        },
        "gate_passed": {
            "mean": float(np.mean(gate)) if gate.size > 0 else 0.0,
            "zero_rate": float(np.mean(gate == 0)) if gate.size > 0 else 0.0,
            "distribution": {str(k): int(v) for k, v in sorted(Counter(gate).items())},
        },
        "reject_reasons": dict(reject_counter),
        "stage1_segments": {
            "mean_segments_per_frame": float(np.mean(segment_counts)) if segment_counts.size > 0 else 0.0,
            "mean_segment_length": float(np.mean(seg_len)) if seg_len.size > 0 else 0.0,
        },
    }


def render_timeline(
    map_image_path: Path,
    map_resolution: float,
    map_origin: Tuple[float, float],
    log_rows: List[Dict[str, str]],
    diag_rows: List[Dict[str, str]],
    out_dir: Path,
    stride: int,
    max_frames: int,
    fps: int,
    disable_gif: bool,
) -> Dict[str, object]:
    lidar_rows = [row for row in log_rows if row.get("lidar_updated") == "1"]
    if not lidar_rows:
        raise RuntimeError("No lidar_updated=1 rows found in localization log")

    image = plt.imread(map_image_path)
    if image.ndim == 3:
        image = image[..., 0]

    h, w = image.shape[:2]
    x0, y0 = map_origin
    extent = [x0, x0 + w * map_resolution, y0, y0 + h * map_resolution]

    frame_count = min(len(lidar_rows), len(diag_rows)) if diag_rows else len(lidar_rows)
    indices = list(range(0, frame_count, max(1, stride)))
    if max_frames > 0:
        indices = indices[:max_frames]

    frames_dir = out_dir / "timeline_frames"
    frames_dir.mkdir(parents=True, exist_ok=True)

    saved_frames: List[Path] = []
    for out_idx, src_idx in enumerate(indices):
        row = lidar_rows[src_idx]
        diag = diag_rows[src_idx] if src_idx < len(diag_rows) else {}

        true_x = float(row["true_x"])
        true_y = float(row["true_y"])
        true_theta = float(row["true_theta"])
        est_x = float(row["est_x"])
        est_y = float(row["est_y"])

        scan_points_robot = parse_points_robot(row.get("scan_points_robot", ""))
        scan_points_world = [
            transform_point_robot_to_world(xr, yr, true_x, true_y, true_theta)
            for xr, yr in scan_points_robot
        ]

        fig, ax = plt.subplots(figsize=(8, 8), dpi=120)
        ax.imshow(image, cmap="gray", origin="upper", extent=extent)

        if scan_points_world:
            arr = np.asarray(scan_points_world, dtype=float)
            ax.scatter(arr[:, 0], arr[:, 1], s=4, c="cyan", alpha=0.6, label="scan")

        ax.scatter([true_x], [true_y], c="lime", s=32, label="true")
        ax.scatter([est_x], [est_y], c="magenta", s=28, label="estimate")

        for x1r, y1r, x2r, y2r in parse_segments(diag.get("stage1_segments", "")):
            x1w, y1w = transform_point_robot_to_world(x1r, y1r, true_x, true_y, true_theta)
            x2w, y2w = transform_point_robot_to_world(x2r, y2r, true_x, true_y, true_theta)
            ax.plot([x1w, x2w], [y1w, y2w], color="yellow", linewidth=2.0, alpha=0.9)

        step = int(row["step"])
        time_s = float(row["time"])
        stage1 = diag.get("stage1_extracted", "?")
        stage2 = diag.get("stage2_matches", "?")
        gate = diag.get("gate_passed", "?")
        accepted = diag.get("accepted", "?")
        reject = diag.get("reject", "-")

        ax.set_title(
            "RANSAC debug timeline "
            f"step={step} time={time_s:.2f}s\n"
            f"stage1={stage1} stage2={stage2} gate={gate} accepted={accepted} reject={reject}"
        )
        ax.set_xlabel("x [m]")
        ax.set_ylabel("y [m]")
        ax.set_aspect("equal")
        ax.grid(alpha=0.2)
        ax.legend(loc="upper right")

        out_path = frames_dir / f"frame_{out_idx:04d}.png"
        fig.tight_layout()
        fig.savefig(out_path)
        plt.close(fig)
        saved_frames.append(out_path)

    gif_path = out_dir / "ransac_debug_timeline.gif"
    gif_saved = False
    if not disable_gif and saved_frames:
        try:
            from PIL import Image

            images = [Image.open(path) for path in saved_frames]
            duration_ms = int(1000 / max(1, fps))
            images[0].save(
                gif_path,
                save_all=True,
                append_images=images[1:],
                duration=duration_ms,
                loop=0,
            )
            for image_obj in images:
                image_obj.close()
            gif_saved = True
        except Exception as exc:
            print(f"GIF export skipped: {exc}")

    return {
        "rendered_frames": len(saved_frames),
        "aligned_frames": frame_count,
        "frame_dir": str(frames_dir),
        "gif_saved": gif_saved,
        "gif_path": str(gif_path) if gif_saved else "",
    }


def main() -> int:
    args = parse_args()

    app_exit_code = None
    if not args.skip_run:
        app_exit_code = run_localization_test(args)

    header, _columns, log_rows = parse_header_and_rows(args.log)
    diag_rows = parse_diag_rows(args.diag_log)

    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if diag_rows:
        stage1 = as_int(diag_rows, "stage1_extracted")
        stage2 = as_int(diag_rows, "stage2_matches")
        gate = as_int(diag_rows, "gate_passed")
        reject_counter = Counter(row.get("reject", "") for row in diag_rows if "reject" in row)

        save_timeseries(out_dir / "stage1_extracted_timeseries.png", "Stage1 extracted lines", "count", stage1)
        save_timeseries(out_dir / "stage2_matches_timeseries.png", "Stage2 matches", "count", stage2)
        save_timeseries(out_dir / "gate_passed_timeseries.png", "Gate passed", "count", gate)
        save_histogram(out_dir / "stage1_extracted_histogram.png", "Stage1 extracted distribution", stage1)
        save_histogram(out_dir / "stage2_matches_histogram.png", "Stage2 matches distribution", stage2)
        save_reject_bar(out_dir / "reject_reasons.png", reject_counter)
        save_stage1_segment_grid(out_dir / "stage1_segments_grid.png", diag_rows)

    scenario_path = resolve_scenario_path(header, args.scenario)
    map_image_path, map_resolution, map_origin = parse_scenario_and_map(scenario_path)
    timeline = render_timeline(
        map_image_path=map_image_path,
        map_resolution=map_resolution,
        map_origin=map_origin,
        log_rows=log_rows,
        diag_rows=diag_rows,
        out_dir=out_dir,
        stride=args.stride,
        max_frames=args.max_frames,
        fps=args.fps,
        disable_gif=args.no_gif,
    )

    summary = {
        "app_exit_code": app_exit_code,
        "stdout_log": str(args.stdout_log),
        "diag_log": str(args.diag_log),
        "localization_log": str(args.log),
        "scenario": str(scenario_path),
        "diag_frames": len(diag_rows),
        "diag_metrics": build_diag_metrics(diag_rows) if diag_rows else {},
        "timeline": timeline,
    }

    summary_path = out_dir / "ransac_debug_summary.json"
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Saved summary: {summary_path}")
    if timeline.get("gif_saved"):
        print(f"Saved GIF: {timeline['gif_path']}")
    else:
        print("GIF: not saved")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
